name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:latest
